[package]
name = "rexif"
version = "0.2.0"
authors = ["Elvis Pfützenreuter <epxx@epxx.co>"]
exclude = ["samples/"]

[lib]
name = "rexif"
path = "src/lib.rs"

[[bin]]
name = "rexiftool"
path = "src/main.rs"
